# Generated by Django 2.2.7 on 2020-04-15 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_statusmessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatusMessage',
        ),
    ]
