# Generated by Django 2.2.7 on 2020-04-16 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0008_auto_20200416_0135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
