# Generated by Django 2.2.7 on 2020-04-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_usersrecipes'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersrecipes',
            name='timestamp',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
