# Generated by Django 2.2.7 on 2020-04-21 14:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_usersrecipes_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='statusmessage',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='project.Project'),
            preserve_default=False,
        ),
    ]
