# Generated by Django 2.2.7 on 2020-04-21 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_statusmessage_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statusmessage',
            name='project',
        ),
    ]
