# Generated by Django 2.2.7 on 2020-04-24 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0016_project_cooktime'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Project',
            new_name='Recipe',
        ),
    ]
