# Generated by Django 2.2.7 on 2020-04-27 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0017_auto_20200424_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statusmessage',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
